apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx
spec:
  dnsNames:
  - test.s0.lakis.eu
  duration: 2160h0m0s
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: le-default
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048          
  renewBefore: 720h0m0s
  secretName: nginx-cert
  subject:
    organizations:
    - LAKIS
  usages:
  - server auth
  - client auth
