apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx
  labels:
    app: nginx
    app.kubernetes.io/name: nginx
spec:
  rules:
    - host: "nginx-test.lakis.tech"
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx
              servicePort: 80
