apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nginx-test
spec:
  interval: 24h
  path: "./nginx-test/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: h1
  timeout: 5m
